#!/usr/bin/env python3
"""Interactive CLI to bootstrap .env and config.yaml. Supports dual-key (demo + live) and demo-first burn-in."""

import os
from pathlib import Path


def _read_existing_env() -> dict[str, str]:
    """Read existing .env without overwriting secrets we are not re-prompting for."""
    env_path = Path(".env")
    if not env_path.exists():
        return {}
    out = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip()
    return out


def main() -> None:
    """Interactive bootstrap. Prompts for demo keys (recommended); optionally live keys."""
    print("=== Money Flow Momentum - Config Bootstrap ===\n")
    print("Dual-key mode: set demo and live keys separately. BYBIT_ENV=demo|live selects which pair is used.")
    print("Demo keys: create from mainnet account -> Demo Trading. Do not use testnet for demo.\n")

    existing = _read_existing_env()

    # Demo keys (recommended for burn-in)
    default_demo_key = existing.get("BYBIT_DEMO_API_KEY", existing.get("BYBIT_API_KEY", ""))
    default_demo_secret = existing.get("BYBIT_DEMO_API_SECRET", existing.get("BYBIT_API_SECRET", ""))
    demo_key = input("Bybit DEMO API Key (from mainnet account Demo Trading): ").strip() or default_demo_key
    demo_secret = input("Bybit DEMO API Secret: ").strip() or default_demo_secret

    add_live = input("Add LIVE/mainnet keys now? (y/n): ").strip().lower() in ("y", "yes", "1")
    live_key = ""
    live_secret = ""
    if add_live:
        live_key = input("Bybit LIVE API Key: ").strip() or existing.get("BYBIT_LIVE_API_KEY", "")
        live_secret = input("Bybit LIVE API Secret: ").strip() or existing.get("BYBIT_LIVE_API_SECRET", "")

    default_env = existing.get("BYBIT_ENV", "demo").strip().lower()
    if default_env not in ("demo", "live", "testnet"):
        default_env = "demo"
    env_choice = input("Default BYBIT_ENV (demo/live/testnet) [demo]: ").strip().lower() or default_env or "demo"
    if env_choice not in ("demo", "live", "testnet"):
        env_choice = "demo"

    risk_pct = input("Risk per trade % (default 0.5): ").strip() or "0.5"
    max_pos = input("Max concurrent positions (default 5): ").strip() or "5"

    # Build .env: demo + live dual-key preferred
    env_lines = [
        "# Generated by bootstrap_config.py - DO NOT COMMIT",
        "# Environment: demo (burn-in) | live | testnet (legacy)",
        "BYBIT_ENV=" + env_choice,
        "BYBIT_DEMO_API_KEY=" + demo_key,
        "BYBIT_DEMO_API_SECRET=" + demo_secret,
        "BYBIT_LIVE_API_KEY=" + live_key,
        "BYBIT_LIVE_API_SECRET=" + live_secret,
    ]
    if existing.get("BYBIT_API_KEY") or existing.get("BYBIT_API_SECRET"):
        env_lines.append("# Legacy (kept from existing .env)")
        env_lines.append("BYBIT_API_KEY=" + existing.get("BYBIT_API_KEY", ""))
        env_lines.append("BYBIT_API_SECRET=" + existing.get("BYBIT_API_SECRET", ""))
    else:
        env_lines.append("# Legacy fallback (uncomment to use single key pair)")
        env_lines.append("# BYBIT_API_KEY=")
        env_lines.append("# BYBIT_API_SECRET=")

    env_path = Path(".env")
    env_path.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    os.chmod(env_path, 0o600)
    print(f"\nWrote {env_path} (mode 600)")

    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)
    # exchange.testnet is overridden by load_config from BYBIT_ENV (only true when env=testnet)
    config_content = f"""# Generated by bootstrap_config.py
mode: paper

exchange:
  testnet: {str(env_choice == 'testnet').lower()}
  one_way_mode: true
  default_leverage: 5

universe:
  min_24h_turnover_usdt: 1000000
  max_spread_bps: 50
  allowlist: []
  blocklist: []

risk:
  risk_per_trade_pct: {risk_pct}
  max_concurrent_positions: {int(max_pos)}
  max_daily_drawdown_pct: 5.0
"""
    config_path = config_dir / "config.yaml"
    config_path.write_text(config_content, encoding="utf-8")
    print(f"Wrote {config_path}")

    print("\nDone. Validate: python run_bot.py validate")
    print("Demo burn-in: BYBIT_ENV=demo, then ./scripts/start_testnet_burnin.sh (or run_bot.py run)")
    print("Guarded live: set BYBIT_ENV=live and burn_in_phase: live_small when ready; ./scripts/check_small_live_ready.sh")