#!/usr/bin/env python3
"""Interactive CLI to bootstrap .env and config.yaml."""

import os
from pathlib import Path


def main() -> None:
    """Interactive bootstrap."""
    print("=== Money Flow Momentum - Config Bootstrap ===\n")

    api_key = input("Bybit API Key: ").strip()
    api_secret = input("Bybit API Secret: ").strip()
    testnet = input("Use testnet? (y/n): ").strip().lower() in ("y", "yes", "1")
    risk_pct = input("Risk per trade % (default 0.5): ").strip() or "0.5"
    max_pos = input("Max concurrent positions (default 5): ").strip() or "5"
    account_size = input("Base account size USDT (default 10000): ").strip() or "10000"

    # Write .env
    env_path = Path(".env")
    env_content = f"""# Generated by bootstrap_config.py - DO NOT COMMIT
BYBIT_API_KEY={api_key}
BYBIT_API_SECRET={api_secret}
BYBIT_TESTNET={'true' if testnet else 'false'}
"""
    env_path.write_text(env_content, encoding="utf-8")
    os.chmod(env_path, 0o600)
    print(f"\nWrote {env_path} (mode 600)")

    # Write config
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)
    config_path = config_dir / "config.yaml"
    config_content = f"""# Generated by bootstrap_config.py
mode: paper

exchange:
  testnet: {'true' if testnet else 'false'}
  one_way_mode: true
  default_leverage: 5

universe:
  min_24h_turnover_usdt: 1000000
  max_spread_bps: 50
  allowlist: []
  blocklist: []

risk:
  risk_per_trade_pct: {risk_pct}
  max_concurrent_positions: {int(max_pos)}
  max_daily_drawdown_pct: 5.0

# Account size estimate for position sizing
# account_size_usdt: {account_size}
"""
    config_path.write_text(config_content, encoding="utf-8")
    print(f"Wrote {config_path}")

    print("\nDone. Run: python run_bot.py run")


if __name__ == "__main__":
    main()
