#!/bin/bash
# Operator menu: two canonical modes — demo_research | live_guarded. Commands grouped by mode and workflow.
# Usage: ./scripts/operator_menu.sh

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "=== Money Flow Momentum — Operator commands ==="
echo ""
echo "Operating modes (config: operating_mode in config/config.yaml)"
echo "  demo_research   — autonomous Demo research/tuning (BYBIT_ENV=demo, burn_in_phase: demo)"
echo "  live_guarded    — guarded live trading (BYBIT_ENV=live, manual approval for config promotion and Demo→Live)"
echo ""
echo "--- Install / bootstrap ---"
echo "  ./install.sh"
echo "  python bootstrap_config.py"
echo "  python run_bot.py validate                    # shows operating_mode and mode-ready message"
echo ""
echo "--- Systemd (main bot + automation timer) ---"
echo "  ./scripts/install_systemd.sh"
echo "  sudo systemctl start money-flow-momentum"
echo "  sudo systemctl enable money-flow-momentum-automation.timer && sudo systemctl start money-flow-momentum-automation.timer"
echo "  ./scripts/service_status.sh"
echo "  ./scripts/service_status.sh bot | automation"
echo "  ./scripts/tail_logs.sh [lines]"
echo "  ./scripts/automation_status.sh"
echo ""
echo "--- Demo research (demo_research) ---"
echo "  ./scripts/start_testnet_burnin.sh [--foreground]"
echo "  ./scripts/check_burnin.sh"
echo "  ./scripts/show_runtime_mode.sh"
echo ""
echo "--- Guarded live (live_guarded) — readiness and start ---"
echo "  ./scripts/check_small_live_ready.sh"
echo "  python run_bot.py promote-env                    # preview Demo → Live"
echo "  python run_bot.py promote-env --confirm-live      # apply switch to live_guarded"
echo "  ./scripts/promote_demo_to_live.sh [--confirm-live] [--start-live]"
echo "  ./scripts/start_small_live.sh [--foreground]"
echo ""
echo "--- Incident / stop ---"
echo "  ./scripts/incident_stop.sh [--rollback \"reason\"]"
echo ""
echo "--- Evaluate / optimize / shadow / promote (manual gates) ---"
echo "  python run_bot.py evaluate [--from-date YYYY-MM-DD] [--to-date YYYY-MM-DD]"
echo "  python run_bot.py optimize run [--config-id <id>]"
echo "  python run_bot.py optimize report <run_id>"
echo "  python run_bot.py shadow start --candidate-config-id <id>"
echo "  python run_bot.py shadow report <candidate_config_id>"
echo "  python run_bot.py promote --config-id <id>"
echo "  python run_bot.py promote status"
echo "  python run_bot.py post-burnin [--from-date ...] [--start-shadow] [--shadow-report]"
echo "  python run_bot.py config rollback [--reason \"reason\"]"
echo ""
echo "--- Reporting ---"
echo "  ./scripts/generate_burnin_bundle.sh [output_dir]"
echo "  ./scripts/backup_config.sh [--timestamp]"
echo ""
echo "--- Direct CLI ---"
echo "  python run_bot.py health"
echo "  python run_bot.py status"
echo "  python run_bot.py burnin status | report | readiness --output artifacts/burnin"
