#!/bin/bash
# Operator menu: list main commands for install, validate, burn-in, live, stop, evaluate, optimize, shadow, promote/rollback.
# Usage: ./scripts/operator_menu.sh

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

echo "=== Money Flow Momentum — Operator commands ==="
echo ""
echo "Install / bootstrap"
echo "  ./install.sh"
echo "  python bootstrap_config.py"
echo "  python run_bot.py validate"
echo ""
echo "Systemd (main bot + automation timer)"
echo "  ./scripts/install_systemd.sh              # install main service + automation timer"
echo "  sudo systemctl start money-flow-momentum   # start trading bot"
echo "  sudo systemctl enable money-flow-momentum-automation.timer && sudo systemctl start money-flow-momentum-automation.timer  # enable/start automation cycle (every 15 min)"
echo "  ./scripts/service_status.sh               # status of bot + automation timer"
echo "  ./scripts/service_status.sh bot           # main bot only"
echo "  ./scripts/service_status.sh automation     # automation timer + last run"
echo "  ./scripts/tail_logs.sh [lines]             # tail bot log"
echo "  ./scripts/tail_logs.sh automation [lines]  # tail automation cycle journal"
echo "  ./scripts/automation_status.sh            # automation status + recommendation artifact"
echo ""
echo "Demo burn-in"
echo "  ./scripts/start_testnet_burnin.sh [--foreground]"
echo "  ./scripts/check_burnin.sh"
echo "  ./scripts/show_runtime_mode.sh"
echo ""
echo "Small-live readiness and start"
echo "  ./scripts/check_small_live_ready.sh"
echo "  python run_bot.py promote-env                    # preview Demo -> Live"
echo "  python run_bot.py promote-env --confirm-live     # apply switch to Live"
echo "  ./scripts/promote_demo_to_live.sh [--confirm-live] [--start-live]"
echo "  ./scripts/start_small_live.sh [--foreground]"
echo ""
echo "Incident / stop"
echo "  ./scripts/incident_stop.sh [--rollback \"reason\"]"
echo ""
echo "Evaluate / optimize / shadow / promote"
echo "  python run_bot.py evaluate [--from-date YYYY-MM-DD] [--to-date YYYY-MM-DD]"
echo "  python run_bot.py optimize run [--config-id <id>]"
echo "  python run_bot.py optimize report <run_id>"
echo "  python run_bot.py shadow start --candidate-config-id <id>"
echo "  python run_bot.py shadow report <candidate_config_id>"
echo "  python run_bot.py promote --config-id <id>"
echo "  python run_bot.py promote status"
echo "  python run_bot.py post-burnin [--from-date YYYY-MM-DD] [--to-date YYYY-MM-DD] [--start-shadow] [--shadow-report]"
echo "  python run_bot.py config rollback [--reason \"reason\"]"
echo ""
echo "Reporting"
echo "  ./scripts/generate_burnin_bundle.sh [output_dir]"
echo "  ./scripts/backup_config.sh [--timestamp]"
echo ""
echo "Direct CLI"
echo "  python run_bot.py health"
echo "  python run_bot.py status"
echo "  python run_bot.py burnin status | report | readiness --output artifacts/burnin"
